### ISSUE TITLE
MBC1 Letterless

### ISSUE THREAD

**Issue by ogamespec** [Raphael-Boichot/Game-Boy-chips-decapping-project#1]
The MBC1B picture you have now is practically unusable for reverse engineering: typical mistake of those who photograph chips but don't analyze them - they try to focus on both poly and m1/m2, and end up with a mess that can't be analyzed.

Here you can see M1 better and easily reconstruct the schematics of Gate Array cells:

![image](https://github.com/Raphael-Boichot/Game-Boy-chips-decapping-project/assets/5828819/2099c296-96cc-4bde-9713-7c5fce789bd5)

https://drive.google.com/drive/u/2/folders/12aB6VAzrLOIOzGgljAT-jHwqS2w8JxUf

BTW, the description of depackaging the chips and getting a photo of them is done rather eclectically, in fact anyone "on their knees" can do it:
https://github.com/emu-russia/dmgcpu/blob/main/methods.md

You can use my MBC1 pictures without attribution, no problem, it doesn't make much sense.

Good luck! 😸

**Comment by Raphael-Boichot** [comment]
And what ?
